## Settings
title: "www.DC602.org"
owner: ""
url: "https://www.dc602.org/"
email: ""
github: "dc602"
baseurl: "/"
permalink: /:title/
description: ""
markdown: kramdown
maximize: false
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 1
# texts randomly displayed in background
bgtext: "DC602αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
